### ISSUE TITLE
Rockspec is broken, it seems.

### ISSUE THREAD

**Issue by aensidhe** [igorcoding/tarantool-spacer#4]
Dockerfile excerpt:

```
ENV \
    LUAROCK_SPACER_REPO=https://github.com/igorcoding/tarantool-spacer.git \
    LUAROCK_SPACER_TAG=b8c55ab

RUN git clone $LUAROCK_SPACER_REPO /rocks/spacer \
    && git -C /rocks/spacer checkout $LUAROCK_SPACER_TAG \
    && (cd /rocks/spacer && luarocks make *rockspec) \
```

Fails with:
```
+ luarocks make spacer-scm-1.rockspec

Error: Build error: Failed installing spacer.lua in /usr/local/lib/luarocks/rocks/spacer/scm-1/lua/spacer.lua: spacer.lua: No such file or directory
```

**Comment by igorcoding** [comment]
Hello, for version 2 you should use one of the rockspecs in the `rockspecs` folder, not the one in the root.
I'm sorry for the inconvenience with this scm-1.rockspec as it is here only for reverse compatibility with projects that already rely on the spacer version 1.

**Comment by igorcoding** [comment]
Scm-1 is working correctly and install from v1 branch if you install it using luarocks install https://path/to/rockspec

**Comment by aensidhe** [comment]
> Hello, for version 2 you should use one of the rockspecs in the rockspecs folder, not the one in the root.

Works like a charm, thanks.
