### ISSUE TITLE
field type 'num' is deprecated since Tarantool 1.7, please use 'unsigned' instead

### ISSUE THREAD

**Issue by bofm** [igorcoding/tarantool-spacer#7]
I get the error:
```
2018-07-11 16:34:36.745 [1] main/101/app.lua schema.lua:790 W> field type 'num' is deprecated since Tarantool 1.7, please use 'unsigned' instead
```
on Tarantool 1.10 when I define a space with a field of type 'number'.

**Comment by bofm** [comment]
This is most likely caused by improper version comparison code in compat.lua. It compares versions as strings.

**Comment by igorcoding** [comment]
Fixed in https://github.com/igorcoding/tarantool-spacer/releases/tag/v2.1.2
