### ISSUE TITLE
Documentation version mismatch

### ISSUE THREAD

**Issue by d9k** [igorcoding/tarantool-spacer#9]
Hi!

I install `spacer` with

`luarocks install https://raw.githubusercontent.com/igorcoding/tarantool-spacer/master/rockspecs/spacer-2.1.2-1.rockspec`

or 

`luarocks install https://raw.githubusercontent.com/igorcoding/tarantool-spacer/master/rockspecs/spacer-scm-2.rockspec`

command.

When  I run command

```
box.spacer = require 'spacer'.new({
    migrations = 'path/to/migrations/folder',
})
```

(as advised in documentation on `master` branch) I get an error `attempt to call field ''new'' (a nil value)'`

The tarantool chat helped me to understand that documentation is obsolete and I need to install `spacer` from `rockspecs/spacer-scm-3.rockspec` (`source` at rockfile points to `master` branch) and not from  `rockspecs/spacer-scm-2.rockspec` (source points to `v2` branch)

I would be happy to see documentation fixed ;-)

**Comment by igorcoding** [comment]
FIxed, thank you!
